// appship upload (MVP 2): thin wrapper that hands a built artifact to the
// fastlane lanes generated by `appship export fastlane`. AppShip never talks
// to the stores directly — fastlane owns auth and the upload protocol
// (TRD §1: deployment layer is delegated, not reimplemented).

import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile, stat } from 'node:fs/promises';
import { join } from 'node:path';
import glob from 'fast-glob';

export class UploadError extends Error {}

export type UploadPlatform = 'ios' | 'android';

const ARTIFACT_GLOBS: Record<UploadPlatform, string[]> = {
  ios: ['*.ipa', 'build/**/*.ipa', 'ios/build/**/*.ipa'],
  android: [
    '*.aab',
    'android/app/build/outputs/bundle/**/*.aab',
    'app/build/outputs/bundle/**/*.aab',
    'build/**/*.aab',
  ],
};

const ARTIFACT_IGNORE = ['**/node_modules/**', '**/Pods/**', '**/.git/**'];

export const UPLOAD_LANES: Record<UploadPlatform, string> = {
  ios: 'upload_testflight',
  android: 'upload_build',
};

/** Newest matching artifact by mtime, or null. */
export async function findArtifact(
  projectRoot: string,
  platform: UploadPlatform,
): Promise<string | null> {
  const matches = await glob(ARTIFACT_GLOBS[platform], {
    cwd: projectRoot,
    ignore: ARTIFACT_IGNORE,
  });
  if (matches.length === 0) return null;
  const withTimes = await Promise.all(
    matches.map(async (path) => ({
      path,
      mtime: (await stat(join(projectRoot, path))).mtimeMs,
    })),
  );
  withTimes.sort((a, b) => b.mtime - a.mtime);
  return withTimes[0]!.path;
}

export interface FastlaneCommand {
  command: string;
  prefixArgs: string[];
}

/**
 * Prefer `bundle exec fastlane` when the project has a Gemfile (the setup
 * fastlane itself recommends); otherwise fall back to a global fastlane.
 */
export function resolveFastlaneCommand(
  projectRoot: string,
  hasGlobalFastlane: boolean,
): FastlaneCommand | null {
  if (existsSync(join(projectRoot, 'Gemfile'))) {
    return { command: 'bundle', prefixArgs: ['exec', 'fastlane'] };
  }
  if (hasGlobalFastlane) {
    return { command: 'fastlane', prefixArgs: [] };
  }
  return null;
}

export async function assertUploadLane(
  projectRoot: string,
  platform: UploadPlatform,
): Promise<void> {
  const fastfilePath = join(projectRoot, 'fastlane', 'Fastfile');
  if (!existsSync(fastfilePath)) {
    throw new UploadError(
      'fastlane/Fastfile not found. Run `appship export fastlane` first.',
    );
  }
  const fastfile = await readFile(fastfilePath, 'utf8');
  const lane = UPLOAD_LANES[platform];
  if (!fastfile.includes(`lane :${lane}`)) {
    throw new UploadError(
      `fastlane/Fastfile has no :${lane} lane. Re-export with ` +
        '`appship export fastlane --force` (or add the lane yourself).',
    );
  }
}

export interface UploadPlan {
  platform: UploadPlatform;
  artifact: string;
  /** e.g. "TestFlight" or "Play track \"internal\"" */
  destination: string;
  fastlaneArgs: string[];
}

export function buildUploadPlan(
  platform: UploadPlatform,
  artifact: string,
  track: string,
): UploadPlan {
  if (platform === 'ios') {
    return {
      platform,
      artifact,
      destination: 'TestFlight',
      fastlaneArgs: ['ios', UPLOAD_LANES.ios, `ipa:${artifact}`],
    };
  }
  return {
    platform,
    artifact,
    destination: `Play track "${track}"`,
    fastlaneArgs: ['android', UPLOAD_LANES.android, `aab:${artifact}`, `track:${track}`],
  };
}

export type CommandRunner = (
  command: string,
  args: string[],
  cwd: string,
) => Promise<number>;

/** Default runner: inherit stdio so fastlane's own output/prompts show through. */
export const spawnRunner: CommandRunner = (command, args, cwd) =>
  new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: 'inherit' });
    child.on('error', reject);
    child.on('close', (code) => resolve(code ?? 1));
  });

export async function runUpload(
  projectRoot: string,
  fastlane: FastlaneCommand,
  plan: UploadPlan,
  runner: CommandRunner = spawnRunner,
): Promise<number> {
  return runner(fastlane.command, [...fastlane.prefixArgs, ...plan.fastlaneArgs], projectRoot);
}
