import { mkdir, mkdtemp, rm, utimes, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { appshipConfigSchema } from '../config/schema.js';
import { fastfileContent } from '../fastlane/index.js';
import {
  assertUploadLane,
  buildUploadPlan,
  findArtifact,
  resolveFastlaneCommand,
  runUpload,
  UploadError,
  type CommandRunner,
} from './index.js';

describe('findArtifact', () => {
  let tempRoot: string;

  beforeEach(async () => {
    tempRoot = await mkdtemp(join(tmpdir(), 'appship-upload-'));
  });

  afterEach(async () => {
    await rm(tempRoot, { recursive: true, force: true });
  });

  it('returns null when nothing is built', async () => {
    expect(await findArtifact(tempRoot, 'android')).toBeNull();
  });

  it('picks the newest artifact by mtime', async () => {
    const bundleDir = join(tempRoot, 'android/app/build/outputs/bundle/release');
    await mkdir(bundleDir, { recursive: true });
    const oldPath = join(bundleDir, 'app-old.aab');
    const newPath = join(tempRoot, 'fresh.aab');
    await writeFile(oldPath, 'old');
    await writeFile(newPath, 'new');
    const past = new Date(Date.now() - 60_000);
    await utimes(oldPath, past, past);

    expect(await findArtifact(tempRoot, 'android')).toBe('fresh.aab');
  });

  it('ignores node_modules', async () => {
    await mkdir(join(tempRoot, 'node_modules/pkg'), { recursive: true });
    await writeFile(join(tempRoot, 'node_modules/pkg/x.ipa'), 'x');
    expect(await findArtifact(tempRoot, 'ios')).toBeNull();
  });
});

describe('resolveFastlaneCommand', () => {
  let tempRoot: string;

  beforeEach(async () => {
    tempRoot = await mkdtemp(join(tmpdir(), 'appship-upload-'));
  });

  afterEach(async () => {
    await rm(tempRoot, { recursive: true, force: true });
  });

  it('prefers bundle exec when a Gemfile exists', async () => {
    await writeFile(join(tempRoot, 'Gemfile'), 'gem "fastlane"\n');
    expect(resolveFastlaneCommand(tempRoot, true)).toEqual({
      command: 'bundle',
      prefixArgs: ['exec', 'fastlane'],
    });
  });

  it('falls back to global fastlane, or null when unavailable', () => {
    expect(resolveFastlaneCommand('/nonexistent', true)).toEqual({
      command: 'fastlane',
      prefixArgs: [],
    });
    expect(resolveFastlaneCommand('/nonexistent', false)).toBeNull();
  });
});

describe('assertUploadLane', () => {
  let tempRoot: string;

  beforeEach(async () => {
    tempRoot = await mkdtemp(join(tmpdir(), 'appship-upload-'));
  });

  afterEach(async () => {
    await rm(tempRoot, { recursive: true, force: true });
  });

  it('rejects when the Fastfile is missing', async () => {
    await expect(assertUploadLane(tempRoot, 'ios')).rejects.toThrow(UploadError);
  });

  it('rejects when the lane is missing (old export)', async () => {
    await mkdir(join(tempRoot, 'fastlane'), { recursive: true });
    await writeFile(join(tempRoot, 'fastlane/Fastfile'), 'lane :upload_metadata do\nend\n');
    await expect(assertUploadLane(tempRoot, 'android')).rejects.toThrow(/upload_build/);
  });

  it('accepts the Fastfile generated by appship export fastlane', async () => {
    const config = appshipConfigSchema.parse({
      project: { name: 'App', description: 'x' },
      platforms: {
        ios: { bundle_id: 'com.example.app' },
        android: { package_name: 'com.example.app' },
      },
      stores: {},
    });
    await mkdir(join(tempRoot, 'fastlane'), { recursive: true });
    await writeFile(join(tempRoot, 'fastlane/Fastfile'), fastfileContent(config));
    await expect(assertUploadLane(tempRoot, 'ios')).resolves.toBeUndefined();
    await expect(assertUploadLane(tempRoot, 'android')).resolves.toBeUndefined();
  });
});

describe('buildUploadPlan / runUpload', () => {
  it('builds the TestFlight invocation', () => {
    const plan = buildUploadPlan('ios', 'build/MyApp.ipa', 'internal');
    expect(plan.destination).toBe('TestFlight');
    expect(plan.fastlaneArgs).toEqual(['ios', 'upload_testflight', 'ipa:build/MyApp.ipa']);
  });

  it('builds the Play track invocation with the chosen track', () => {
    const plan = buildUploadPlan('android', 'app.aab', 'beta');
    expect(plan.destination).toBe('Play track "beta"');
    expect(plan.fastlaneArgs).toEqual(['android', 'upload_build', 'aab:app.aab', 'track:beta']);
  });

  it('invokes fastlane through the resolved command and returns its exit code', async () => {
    const calls: Array<{ command: string; args: string[]; cwd: string }> = [];
    const fakeRunner: CommandRunner = async (command, args, cwd) => {
      calls.push({ command, args, cwd });
      return 0;
    };
    const plan = buildUploadPlan('android', 'app.aab', 'internal');
    const code = await runUpload(
      '/project',
      { command: 'bundle', prefixArgs: ['exec', 'fastlane'] },
      plan,
      fakeRunner,
    );
    expect(code).toBe(0);
    expect(calls).toEqual([
      {
        command: 'bundle',
        args: ['exec', 'fastlane', 'android', 'upload_build', 'aab:app.aab', 'track:internal'],
        cwd: '/project',
      },
    ]);
  });
});
