// appship submit (MVP 2): confirmation-gated store submission. Like upload,
// AppShip never talks to the stores directly — it drives the :submit_review
// lanes generated by `appship export fastlane` (deliver submits the latest
// TestFlight build for App Store review; supply promotes a tested Play track).

import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  spawnRunner,
  type CommandRunner,
  type FastlaneCommand,
} from '../upload/index.js';

export class SubmitError extends Error {}

export type SubmitPlatform = 'ios' | 'android';

export const SUBMIT_LANE = 'submit_review';

/**
 * Both platforms share the lane name, so a plain `includes` check (as upload
 * uses) could match the other platform's block. Slice out this platform's
 * `platform :<name> do ... ` section before looking for the lane.
 */
export function platformBlock(fastfile: string, platform: SubmitPlatform): string | null {
  const marker = `platform :${platform} do`;
  const start = fastfile.indexOf(marker);
  if (start === -1) return null;
  const next = fastfile.indexOf('platform :', start + marker.length);
  return next === -1 ? fastfile.slice(start) : fastfile.slice(start, next);
}

export async function assertSubmitLane(
  projectRoot: string,
  platform: SubmitPlatform,
): Promise<void> {
  const fastfilePath = join(projectRoot, 'fastlane', 'Fastfile');
  if (!existsSync(fastfilePath)) {
    throw new SubmitError('fastlane/Fastfile not found. Run `appship export fastlane` first.');
  }
  const block = platformBlock(await readFile(fastfilePath, 'utf8'), platform);
  if (!block || !block.includes(`lane :${SUBMIT_LANE}`)) {
    throw new SubmitError(
      `fastlane/Fastfile has no ${platform} :${SUBMIT_LANE} lane. Re-export with ` +
        '`appship export fastlane --force` (or add the lane yourself).',
    );
  }
}

export interface SubmitOptions {
  /** ios: App Store Connect build number to submit (default: latest uploaded). */
  buildNumber?: string;
  /** android: Play track holding the tested build (default: internal). */
  fromTrack: string;
  /** android: Play track to promote into (default: production). */
  track: string;
}

export interface SubmitPlan {
  platform: SubmitPlatform;
  /** e.g. "App Store review" or "Play track \"production\"" */
  destination: string;
  /** Human-readable facts shown before the confirmation prompt. */
  details: Array<[label: string, value: string]>;
  fastlaneArgs: string[];
}

export function buildSubmitPlan(platform: SubmitPlatform, options: SubmitOptions): SubmitPlan {
  if (platform === 'ios') {
    const args = ['ios', SUBMIT_LANE];
    if (options.buildNumber) args.push(`build_number:${options.buildNumber}`);
    return {
      platform,
      destination: 'App Store review',
      details: [
        ['Build', options.buildNumber ?? 'latest uploaded to App Store Connect'],
        ['Release', 'manual (after approval)'],
      ],
      fastlaneArgs: args,
    };
  }
  return {
    platform,
    destination: `Play track "${options.track}"`,
    details: [['Promote', `"${options.fromTrack}" → "${options.track}"`]],
    fastlaneArgs: [
      'android',
      SUBMIT_LANE,
      `from_track:${options.fromTrack}`,
      `track:${options.track}`,
    ],
  };
}

export async function runSubmit(
  projectRoot: string,
  fastlane: FastlaneCommand,
  plan: SubmitPlan,
  runner: CommandRunner = spawnRunner,
): Promise<number> {
  return runner(fastlane.command, [...fastlane.prefixArgs, ...plan.fastlaneArgs], projectRoot);
}
