import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { appshipConfigSchema } from '../config/schema.js';
import { fastfileContent } from '../fastlane/index.js';
import type { CommandRunner } from '../upload/index.js';
import {
  assertSubmitLane,
  buildSubmitPlan,
  platformBlock,
  runSubmit,
  SubmitError,
} from './index.js';

const BOTH_PLATFORMS = appshipConfigSchema.parse({
  project: { name: 'App', description: 'x' },
  platforms: {
    ios: { bundle_id: 'com.example.app' },
    android: { package_name: 'com.example.app' },
  },
  stores: {},
});

const IOS_ONLY = appshipConfigSchema.parse({
  project: { name: 'App', description: 'x' },
  platforms: { ios: { bundle_id: 'com.example.app' } },
  stores: {},
});

describe('platformBlock', () => {
  it('slices out a single platform section', () => {
    const fastfile = fastfileContent(BOTH_PLATFORMS);
    const ios = platformBlock(fastfile, 'ios')!;
    const android = platformBlock(fastfile, 'android')!;
    expect(ios).toContain('deliver(');
    expect(ios).not.toContain('upload_to_play_store');
    expect(android).toContain('upload_to_play_store');
    expect(android).not.toContain('deliver(');
  });

  it('returns null for a missing platform', () => {
    expect(platformBlock(fastfileContent(IOS_ONLY), 'android')).toBeNull();
  });
});

describe('assertSubmitLane', () => {
  let tempRoot: string;

  beforeEach(async () => {
    tempRoot = await mkdtemp(join(tmpdir(), 'appship-submit-'));
  });

  afterEach(async () => {
    await rm(tempRoot, { recursive: true, force: true });
  });

  it('rejects when the Fastfile is missing', async () => {
    await expect(assertSubmitLane(tempRoot, 'ios')).rejects.toThrow(SubmitError);
  });

  it('rejects when the lane is missing (old export)', async () => {
    await mkdir(join(tempRoot, 'fastlane'), { recursive: true });
    await writeFile(
      join(tempRoot, 'fastlane/Fastfile'),
      'platform :android do\n  lane :upload_build do\n  end\nend\n',
    );
    await expect(assertSubmitLane(tempRoot, 'android')).rejects.toThrow(/submit_review/);
  });

  it('does not accept the other platform’s submit_review lane', async () => {
    await mkdir(join(tempRoot, 'fastlane'), { recursive: true });
    await writeFile(join(tempRoot, 'fastlane/Fastfile'), fastfileContent(IOS_ONLY));
    await expect(assertSubmitLane(tempRoot, 'ios')).resolves.toBeUndefined();
    await expect(assertSubmitLane(tempRoot, 'android')).rejects.toThrow(SubmitError);
  });

  it('accepts the Fastfile generated by appship export fastlane', async () => {
    await mkdir(join(tempRoot, 'fastlane'), { recursive: true });
    await writeFile(join(tempRoot, 'fastlane/Fastfile'), fastfileContent(BOTH_PLATFORMS));
    await expect(assertSubmitLane(tempRoot, 'ios')).resolves.toBeUndefined();
    await expect(assertSubmitLane(tempRoot, 'android')).resolves.toBeUndefined();
  });
});

describe('buildSubmitPlan / runSubmit', () => {
  it('submits the latest iOS build by default', () => {
    const plan = buildSubmitPlan('ios', { fromTrack: 'internal', track: 'production' });
    expect(plan.destination).toBe('App Store review');
    expect(plan.fastlaneArgs).toEqual(['ios', 'submit_review']);
  });

  it('passes an explicit iOS build number through', () => {
    const plan = buildSubmitPlan('ios', {
      buildNumber: '42',
      fromTrack: 'internal',
      track: 'production',
    });
    expect(plan.fastlaneArgs).toEqual(['ios', 'submit_review', 'build_number:42']);
  });

  it('promotes the chosen Play tracks', () => {
    const plan = buildSubmitPlan('android', { fromTrack: 'beta', track: 'production' });
    expect(plan.destination).toBe('Play track "production"');
    expect(plan.fastlaneArgs).toEqual([
      'android',
      'submit_review',
      'from_track:beta',
      'track:production',
    ]);
  });

  it('invokes fastlane through the resolved command and returns its exit code', async () => {
    const calls: Array<{ command: string; args: string[]; cwd: string }> = [];
    const fakeRunner: CommandRunner = async (command, args, cwd) => {
      calls.push({ command, args, cwd });
      return 0;
    };
    const plan = buildSubmitPlan('android', { fromTrack: 'internal', track: 'production' });
    const code = await runSubmit(
      '/project',
      { command: 'bundle', prefixArgs: ['exec', 'fastlane'] },
      plan,
      fakeRunner,
    );
    expect(code).toBe(0);
    expect(calls).toEqual([
      {
        command: 'bundle',
        args: [
          'exec',
          'fastlane',
          'android',
          'submit_review',
          'from_track:internal',
          'track:production',
        ],
        cwd: '/project',
      },
    ]);
  });
});
