// Fastlane export (MVP 2, TRD deployment layer): AppShip stays the AI/
// preparation layer and hands upload off to fastlane. This module maps
// .appship listings into the directory layouts `deliver` (App Store) and
// `supply` (Google Play) consume. Deterministic — no AI, no network.

import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { AppshipConfig } from '../config/schema.js';
import type { GenerateTarget } from '../generate/index.js';

export class FastlaneExportError extends Error {}

export interface FastlaneExportOptions {
  target?: GenerateTarget;
  /** Overwrite existing Appfile/Fastfile scaffolding. Metadata is always rewritten. */
  force?: boolean;
}

export interface FastlaneExportResult {
  written: string[];
  /** Scaffolding files left untouched because they already exist. */
  skipped: string[];
}

/** .appship/app-store/<locale>/<src>.txt → fastlane/metadata/<locale>/<dest>.txt */
const DELIVER_FILE_MAP: Array<[src: string, dest: string]> = [
  ['name', 'name'],
  ['subtitle', 'subtitle'],
  ['description', 'description'],
  ['keywords', 'keywords'],
  ['promotional-text', 'promotional_text'],
  ['release-notes', 'release_notes'],
];

/** .appship/google-play/<locale>/<src>.txt → fastlane/metadata/android/<locale>/<dest>.txt */
const SUPPLY_FILE_MAP: Array<[src: string, dest: string]> = [
  ['title', 'title'],
  ['short-description', 'short_description'],
  ['full-description', 'full_description'],
];

const NON_LOCALE_DIRS = new Set(['privacy', 'screenshots']);

async function listLocales(storeDir: string): Promise<string[]> {
  if (!existsSync(storeDir)) return [];
  const entries = await readdir(storeDir, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory() && !NON_LOCALE_DIRS.has(e.name))
    .map((e) => e.name)
    .sort();
}

async function copyListingFiles(
  projectRoot: string,
  sourceDir: string,
  destDir: string,
  fileMap: Array<[string, string]>,
  written: string[],
): Promise<void> {
  for (const [src, dest] of fileMap) {
    const sourcePath = join(projectRoot, sourceDir, `${src}.txt`);
    if (!existsSync(sourcePath)) continue; // partial listings export what exists
    const destPath = join(destDir, `${dest}.txt`);
    await mkdir(dirname(join(projectRoot, destPath)), { recursive: true });
    await writeFile(join(projectRoot, destPath), await readFile(sourcePath, 'utf8'), 'utf8');
    written.push(destPath);
  }
}

function appfileContent(config: AppshipConfig): string {
  const lines = ['# Generated by appship — fastlane app identity.'];
  if (config.platforms.ios) {
    lines.push(`app_identifier "${config.platforms.ios.bundle_id}"`);
  }
  if (config.platforms.android) {
    lines.push(`package_name "${config.platforms.android.package_name}"`);
    lines.push('# json_key_file "path/to/play-console-service-account.json"');
  }
  return lines.join('\n') + '\n';
}

function fastfileContent(config: AppshipConfig): string {
  const sections: string[] = ['# Generated by appship — metadata upload lanes.'];
  if (config.platforms.ios) {
    sections.push(
      `platform :ios do
  desc "Upload App Store metadata prepared by appship (no binary, no screenshots)"
  lane :upload_metadata do
    deliver(
      metadata_path: "fastlane/metadata",
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true
    )
  end
end`,
    );
  }
  if (config.platforms.android) {
    sections.push(
      `platform :android do
  desc "Upload Google Play metadata prepared by appship (no binary, no images)"
  lane :upload_metadata do
    supply(
      metadata_path: "fastlane/metadata/android",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_changelogs: false
    )
  end
end`,
    );
  }
  return sections.join('\n\n') + '\n';
}

export async function exportFastlane(
  projectRoot: string,
  config: AppshipConfig,
  options: FastlaneExportOptions = {},
): Promise<FastlaneExportResult> {
  const written: string[] = [];
  const skipped: string[] = [];
  const wantIos = options.target !== 'android' && config.platforms.ios !== undefined;
  const wantAndroid = options.target !== 'ios' && config.platforms.android !== undefined;

  const appStoreDir = join(projectRoot, '.appship', 'app-store');
  const playDir = join(projectRoot, '.appship', 'google-play');
  const iosLocales = wantIos ? await listLocales(appStoreDir) : [];
  const androidLocales = wantAndroid ? await listLocales(playDir) : [];

  if (iosLocales.length === 0 && androidLocales.length === 0) {
    throw new FastlaneExportError(
      'No generated store listings found under .appship/. Run `appship generate` first.',
    );
  }

  // deliver: fastlane/metadata/<locale>/
  for (const locale of iosLocales) {
    const destDir = join('fastlane', 'metadata', locale);
    await copyListingFiles(
      projectRoot,
      join('.appship', 'app-store', locale),
      destDir,
      DELIVER_FILE_MAP,
      written,
    );
    if (config.project.support_url) {
      const path = join(destDir, 'support_url.txt');
      await mkdir(dirname(join(projectRoot, path)), { recursive: true });
      await writeFile(join(projectRoot, path), config.project.support_url + '\n', 'utf8');
      written.push(path);
    }
  }

  // deliver review information (not per-locale) from the default locale
  if (iosLocales.length > 0) {
    const reviewSource = join(
      projectRoot,
      '.appship',
      'app-store',
      iosLocales.includes(config.stores.default_locale)
        ? config.stores.default_locale
        : iosLocales[0]!,
      'review-notes.txt',
    );
    if (existsSync(reviewSource)) {
      const path = join('fastlane', 'metadata', 'review_information', 'notes.txt');
      await mkdir(dirname(join(projectRoot, path)), { recursive: true });
      await writeFile(join(projectRoot, path), await readFile(reviewSource, 'utf8'), 'utf8');
      written.push(path);
    }
  }

  // supply: fastlane/metadata/android/<locale>/ (+ changelogs/default.txt)
  for (const locale of androidLocales) {
    const destDir = join('fastlane', 'metadata', 'android', locale);
    await copyListingFiles(
      projectRoot,
      join('.appship', 'google-play', locale),
      destDir,
      SUPPLY_FILE_MAP,
      written,
    );
    const releaseNotes = join(projectRoot, '.appship', 'google-play', locale, 'release-notes.txt');
    if (existsSync(releaseNotes)) {
      const path = join(destDir, 'changelogs', 'default.txt');
      await mkdir(dirname(join(projectRoot, path)), { recursive: true });
      await writeFile(join(projectRoot, path), await readFile(releaseNotes, 'utf8'), 'utf8');
      written.push(path);
    }
  }

  // Scaffolding — never clobber a user's existing fastlane setup without --force
  const scaffolding: Array<[path: string, content: string]> = [
    [join('fastlane', 'Appfile'), appfileContent(config)],
    [join('fastlane', 'Fastfile'), fastfileContent(config)],
  ];
  for (const [path, content] of scaffolding) {
    const absolute = join(projectRoot, path);
    if (existsSync(absolute) && !options.force) {
      skipped.push(path);
      continue;
    }
    await mkdir(dirname(absolute), { recursive: true });
    await writeFile(absolute, content, 'utf8');
    written.push(path);
  }

  return { written, skipped };
}
