// appship screenshots (MVP 2): turn the screenshot plan generated by
// `appship generate` into Maestro flows, then run them. AppShip cannot know
// how to navigate inside the app, so each flow ships with an explicit TODO
// navigation block the developer fills in once — capture refuses to run
// while TODOs remain, so half-configured flows fail loudly, not silently.

import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'yaml';
import { z } from 'zod';
import type { AppshipConfig } from '../config/schema.js';
import type { CommandRunner } from '../upload/index.js';

export class ScreenshotsError extends Error {}

export const FLOWS_DIR = join('.maestro', 'appship');
export const RAW_OUTPUT_DIR = join('.appship', 'screenshots', 'raw');
export const NAVIGATION_TODO = 'TODO(appship): navigate to this screen';

const planSchema = z.object({
  screens: z
    .array(
      z.object({
        screen: z.string().min(1),
        headline: z.string(),
        source_route: z.string().optional(),
      }),
    )
    .default([]),
  note: z.string().optional(),
});

export type ScreenshotPlan = z.infer<typeof planSchema>;

const PLAN_LOCATIONS = [
  join('.appship', 'app-store', 'screenshots', 'screenshot-plan.yml'),
  join('.appship', 'google-play', 'screenshots', 'screenshot-plan.yml'),
];

export async function loadScreenshotPlan(projectRoot: string): Promise<ScreenshotPlan> {
  for (const location of PLAN_LOCATIONS) {
    const path = join(projectRoot, location);
    if (!existsSync(path)) continue;
    const parsed = planSchema.safeParse(parse(await readFile(path, 'utf8')));
    if (!parsed.success) {
      throw new ScreenshotsError(`Invalid screenshot plan (${location}): ${parsed.error.message}`);
    }
    return parsed.data;
  }
  throw new ScreenshotsError(
    'No screenshot plan found under .appship/. Run `appship generate` first.',
  );
}

function slugify(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function flowContent(
  appId: string,
  index: number,
  screen: ScreenshotPlan['screens'][number],
): string {
  const number = String(index + 1).padStart(2, '0');
  const slug = slugify(screen.screen);
  const lines = [
    `# Maestro flow for the "${screen.screen}" screen — generated by appship.`,
    `# Store headline: ${screen.headline}`,
    ...(screen.source_route ? [`# Screen source: ${screen.source_route}`] : []),
    `appId: ${appId}`,
    '---',
    '- launchApp',
    `# ${NAVIGATION_TODO} (then delete this comment)`,
    '# Examples:',
    '#   - tapOn: "Some button text"',
    `#   - openLink: yourapp://${slug}`,
    `- takeScreenshot: ${RAW_OUTPUT_DIR}/${number}-${slug}`,
  ];
  return lines.join('\n') + '\n';
}

export interface GenerateFlowsResult {
  written: string[];
  /** Existing flows left untouched (developer may have filled in navigation). */
  skipped: string[];
}

export async function generateFlows(
  projectRoot: string,
  config: AppshipConfig,
  plan: ScreenshotPlan,
  options: { force?: boolean } = {},
): Promise<GenerateFlowsResult> {
  if (plan.screens.length === 0) {
    throw new ScreenshotsError(
      'The screenshot plan has no screens. Add entries to screenshot-plan.yml ' +
        '(or add screen components under src/screens/ and re-run `appship generate`).',
    );
  }
  // Maestro identifies the app by its id on the device; RN apps usually share
  // one id across platforms. Use android's (emulator is the common Maestro
  // target), falling back to iOS.
  const appId =
    config.platforms.android?.package_name ?? config.platforms.ios?.bundle_id ?? null;
  if (!appId) {
    throw new ScreenshotsError('No platform identifier in appship.yml (platforms.ios/android).');
  }

  const written: string[] = [];
  const skipped: string[] = [];
  await mkdir(join(projectRoot, FLOWS_DIR), { recursive: true });

  for (const [index, screen] of plan.screens.entries()) {
    const number = String(index + 1).padStart(2, '0');
    const path = join(FLOWS_DIR, `${number}-${slugify(screen.screen)}.yaml`);
    const absolute = join(projectRoot, path);
    if (existsSync(absolute) && !options.force) {
      skipped.push(path);
      continue;
    }
    await writeFile(absolute, flowContent(appId, index, screen), 'utf8');
    written.push(path);
  }
  return { written, skipped };
}

export interface CapturePreflight {
  flowFiles: string[];
  /** Flows that still contain the navigation TODO marker. */
  pendingTodos: string[];
}

export async function preflightCapture(projectRoot: string): Promise<CapturePreflight> {
  const flowsDir = join(projectRoot, FLOWS_DIR);
  if (!existsSync(flowsDir)) {
    throw new ScreenshotsError(
      `No Maestro flows found (${FLOWS_DIR}). Run \`appship screenshots flows\` first.`,
    );
  }
  const flowFiles = (await readdir(flowsDir)).filter((f) => f.endsWith('.yaml')).sort();
  if (flowFiles.length === 0) {
    throw new ScreenshotsError(
      `No Maestro flows found (${FLOWS_DIR}). Run \`appship screenshots flows\` first.`,
    );
  }
  const pendingTodos: string[] = [];
  for (const file of flowFiles) {
    const content = await readFile(join(flowsDir, file), 'utf8');
    if (content.includes(NAVIGATION_TODO)) pendingTodos.push(join(FLOWS_DIR, file));
  }
  return { flowFiles, pendingTodos };
}

export async function runCapture(
  projectRoot: string,
  runner: CommandRunner,
  options: { device?: string } = {},
): Promise<number> {
  await mkdir(join(projectRoot, RAW_OUTPUT_DIR), { recursive: true });
  const args = ['test', ...(options.device ? ['--device', options.device] : []), FLOWS_DIR];
  return runner('maestro', args, projectRoot);
}
