import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import glob from 'fast-glob';
import { stringify } from 'yaml';
import { z } from 'zod';
import type { AppshipConfig } from '../config/schema.js';
import type { ScanResult } from '../types.js';
import type { AIProvider } from '../ai/provider.js';
import { buildSummaryPayload } from '../ai/payload.js';
import type { Violation } from '../metadata/validator.js';
import { generateAppStoreListing, generatePlayListing } from './listings.js';
import { generateLegalDoc, LEGAL_DOCS } from './legal.js';
import {
  renderContentRatingYaml,
  renderDataSafetyYaml,
  renderPrivacyQuestionnaireYaml,
} from './privacy-docs.js';
import { renderAppStoreChecklist, renderGooglePlayChecklist } from './checklists.js';

export type GenerateTarget = 'ios' | 'android';

export interface GenerateOptions {
  target?: GenerateTarget; // undefined = both stores
  locales?: string[]; // default: config.stores.locales
  dryRun?: boolean;
}

export interface GeneratedFile {
  /** Path relative to the project root, e.g. ".appship/app-store/en-US/name.txt" */
  path: string;
  content: string;
  violations: Violation[];
}

export interface GenerateResult {
  files: GeneratedFile[];
}

const screenshotPlanSchema = z.object({
  screens: z.array(z.object({ screen: z.string(), headline: z.string() })),
});

const SCREENSHOT_JSON_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['screens'],
  properties: {
    screens: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['screen', 'headline'],
        properties: {
          screen: { type: 'string', description: 'Screen name exactly as given' },
          headline: { type: 'string', description: 'Marketing headline overlay, under 60 characters' },
        },
      },
    },
  },
};

async function detectScreens(projectRoot: string): Promise<Array<{ name: string; route: string }>> {
  const files = await glob(['src/screens/*.{tsx,jsx,ts,js}', 'app/screens/*.{tsx,jsx,ts,js}'], {
    cwd: projectRoot,
    ignore: ['**/node_modules/**', '**/*.test.*'],
  });
  return files.map((route) => ({
    name: (route.split('/').pop() ?? route).replace(/\.(tsx|jsx|ts|js)$/, ''),
    route,
  }));
}

async function buildScreenshotPlan(
  provider: AIProvider,
  projectRoot: string,
  payloadJson: string,
): Promise<string> {
  const screens = await detectScreens(projectRoot);
  const header =
    '# Screenshot plan — generated by appship. Screenshot capture automation\n' +
    '# is planned for a later release; use this as the shot list.\n';
  if (screens.length === 0) {
    return (
      header +
      stringify({
        screens: [],
        note: 'No screen components detected under src/screens or app/screens. Add entries manually.',
      })
    );
  }

  // Screen names only — file paths stay local, routes are added back after.
  const raw = await provider.generateObject({
    system: 'You write short app-store screenshot marketing headlines. Only use the provided app summary; never invent features.',
    prompt:
      `App summary:\n${payloadJson}\n\nScreens: ${screens.map((s) => s.name).join(', ')}\n\n` +
      'Write one headline per screen.',
    jsonSchema: SCREENSHOT_JSON_SCHEMA,
  });
  const plan = screenshotPlanSchema.parse(raw);
  const headlines = new Map(plan.screens.map((s) => [s.screen, s.headline]));

  return (
    header +
    stringify({
      screens: screens.map((s) => ({
        screen: s.name,
        headline: headlines.get(s.name) ?? '[CONFIRM: write a headline]',
        source_route: s.route,
      })),
    })
  );
}

export async function runGenerate(
  projectRoot: string,
  config: AppshipConfig,
  scan: ScanResult,
  provider: AIProvider,
  options: GenerateOptions = {},
): Promise<GenerateResult> {
  const locales = options.locales ?? config.stores.locales;
  const payload = buildSummaryPayload(scan, config);
  const payloadJson = JSON.stringify(payload, null, 2);
  const files: GeneratedFile[] = [];
  const add = (path: string, content: string, violations: Violation[] = []) =>
    files.push({ path: join('.appship', path), content, violations });

  const wantIos = options.target !== 'android';
  const wantAndroid = options.target !== 'ios';

  // Store listings (AI, per locale)
  for (const locale of locales) {
    if (wantIos) {
      const { listing, violations } = await generateAppStoreListing(provider, payload, locale);
      const dir = `app-store/${locale}`;
      add(`${dir}/name.txt`, listing.name + '\n', violations.filter((v) => v.field === 'name'));
      add(`${dir}/subtitle.txt`, listing.subtitle + '\n', violations.filter((v) => v.field === 'subtitle'));
      add(`${dir}/description.txt`, listing.description + '\n', violations.filter((v) => v.field === 'description'));
      add(`${dir}/keywords.txt`, listing.keywords + '\n', violations.filter((v) => v.field === 'keywords'));
      add(`${dir}/promotional-text.txt`, listing.promotionalText + '\n', violations.filter((v) => v.field === 'promotionalText'));
      add(`${dir}/release-notes.txt`, listing.releaseNotes + '\n', violations.filter((v) => v.field === 'releaseNotes'));
      add(`${dir}/review-notes.txt`, listing.reviewNotes + '\n');
    }
    if (wantAndroid) {
      const { listing, violations } = await generatePlayListing(provider, payload, locale);
      const dir = `google-play/${locale}`;
      add(`${dir}/title.txt`, listing.title + '\n', violations.filter((v) => v.field === 'title'));
      add(`${dir}/short-description.txt`, listing.shortDescription + '\n', violations.filter((v) => v.field === 'shortDescription'));
      add(`${dir}/full-description.txt`, listing.fullDescription + '\n', violations.filter((v) => v.field === 'fullDescription'));
      add(`${dir}/release-notes.txt`, listing.releaseNotes + '\n', violations.filter((v) => v.field === 'releaseNotes'));
      add(
        `${dir}/store-settings.yml`,
        stringify({ suggested_category: listing.suggestedCategory, suggested_tags: listing.suggestedTags }),
      );
    }
  }

  // Privacy documents (deterministic)
  if (wantIos) {
    add('app-store/privacy/privacy-questionnaire.yml', renderPrivacyQuestionnaireYaml(scan.privacyReport));
  }
  if (wantAndroid) {
    add('google-play/data-safety.yml', renderDataSafetyYaml(scan.privacyReport));
    add('google-play/content-rating.yml', renderContentRatingYaml(config));
  }

  // Legal drafts (AI)
  for (const spec of LEGAL_DOCS) {
    const doc = await generateLegalDoc(provider, spec, payload, scan.privacyReport);
    add(`legal/${spec.filename}`, doc.endsWith('\n') ? doc : doc + '\n');
  }

  // Screenshot plan (AI headlines when screens are detected)
  const screenshotPlan = await buildScreenshotPlan(provider, projectRoot, payloadJson);
  if (wantIos) add('app-store/screenshots/screenshot-plan.yml', screenshotPlan);
  if (wantAndroid) add('google-play/screenshots/screenshot-plan.yml', screenshotPlan);

  // Checklists (deterministic)
  if (wantIos) add('checklist/app-store.md', renderAppStoreChecklist(config, scan));
  if (wantAndroid) add('checklist/google-play.md', renderGooglePlayChecklist(config, scan));

  if (!options.dryRun) {
    for (const file of files) {
      const absolute = join(projectRoot, file.path);
      await mkdir(dirname(absolute), { recursive: true });
      await writeFile(absolute, file.content, 'utf8');
    }
  }
  return { files };
}

/** Artifact paths runGenerate would produce — used by --dry-run (no AI calls). */
export function planArtifacts(config: AppshipConfig, options: GenerateOptions = {}): string[] {
  const locales = options.locales ?? config.stores.locales;
  const wantIos = options.target !== 'android';
  const wantAndroid = options.target !== 'ios';
  const paths: string[] = [];

  for (const locale of locales) {
    if (wantIos) {
      for (const f of ['name', 'subtitle', 'description', 'keywords', 'promotional-text', 'release-notes', 'review-notes']) {
        paths.push(`.appship/app-store/${locale}/${f}.txt`);
      }
    }
    if (wantAndroid) {
      for (const f of ['title', 'short-description', 'full-description', 'release-notes']) {
        paths.push(`.appship/google-play/${locale}/${f}.txt`);
      }
      paths.push(`.appship/google-play/${locale}/store-settings.yml`);
    }
  }
  if (wantIos) paths.push('.appship/app-store/privacy/privacy-questionnaire.yml');
  if (wantAndroid) {
    paths.push('.appship/google-play/data-safety.yml', '.appship/google-play/content-rating.yml');
  }
  paths.push(...LEGAL_DOCS.map((d) => `.appship/legal/${d.filename}`));
  if (wantIos) paths.push('.appship/app-store/screenshots/screenshot-plan.yml');
  if (wantAndroid) paths.push('.appship/google-play/screenshots/screenshot-plan.yml');
  if (wantIos) paths.push('.appship/checklist/app-store.md');
  if (wantAndroid) paths.push('.appship/checklist/google-play.md');
  return paths;
}
