// Deterministic privacy documents (NO AI — TRD §3): rendered directly from
// scanner findings so every entry is evidence-backed. Data Safety is
// self-reported by the developer, so unconfirmed entries carry explicit
// confirmation markers instead of guessed answers.

import { stringify } from 'yaml';
import type { AppshipConfig } from '../config/schema.js';
import type { PrivacyReport } from '../types.js';

export function renderDataSafetyYaml(report: PrivacyReport): string {
  const header =
    '# Google Play Data Safety draft — generated by appship from code analysis.\n' +
    '# Data Safety answers are the developer\'s self-declaration: review every\n' +
    '# entry, resolve the confirm_before_submitting items, then transcribe into\n' +
    '# the Play Console form.\n';

  const dataCollection: Record<string, unknown> = {};
  for (const [dataType, entry] of Object.entries(report.dataCollection)) {
    dataCollection[dataType] = {
      collected: entry.collected,
      purpose: entry.purpose,
      shared: entry.shared,
      evidence: entry.evidence,
      ...(entry.requiresConfirmation && entry.confirmed === null
        ? { confirm_before_submitting: 'Detection could not determine the exact answer — confirm manually.' }
        : {}),
    };
  }
  return header + stringify({ data_collection: dataCollection });
}

export function renderPrivacyQuestionnaireYaml(report: PrivacyReport): string {
  const header =
    '# Apple privacy questionnaire draft (App Privacy / Nutrition Labels) —\n' +
    '# generated by appship from code analysis. Review before answering in\n' +
    '# App Store Connect.\n';

  const dataTypes = Object.entries(report.dataCollection).map(([dataType, entry]) => ({
    data_type: dataType,
    collected: entry.collected,
    linked_to_user: '[CONFIRM: is this data linked to the user\'s identity?]',
    used_for_tracking: entry.shared
      ? '[CONFIRM: shared with third parties — is it used for tracking?]'
      : false,
    purposes: entry.purpose,
    evidence: entry.evidence,
  }));
  return header + stringify({ privacy_questionnaire: dataTypes });
}

export function renderContentRatingYaml(config: AppshipConfig): string {
  const header =
    '# Google Play content rating questionnaire draft. Every answer must be\n' +
    '# confirmed by the developer — appship cannot infer app content.\n';
  return (
    header +
    stringify({
      content_rating: {
        app_name: config.project.name,
        category: '[CONFIRM: pick the questionnaire category in Play Console]',
        violence: '[CONFIRM]',
        sexuality: '[CONFIRM]',
        language: '[CONFIRM]',
        controlled_substances: '[CONFIRM]',
        user_generated_content: '[CONFIRM: does the app host user-generated content?]',
        user_interaction: '[CONFIRM: can users interact or share location?]',
      },
    })
  );
}
