import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { stringify } from 'yaml';
import { appshipConfigSchema, type AppshipConfig } from '../config/schema.js';
import { CONFIG_FILENAME } from '../config/load.js';
import type { ScanResult } from '../types.js';

export const APPSHIP_DIR = '.appship';

// Used when the user hasn't answered yet (non-interactive init). Doctor
// flags any remaining [CONFIRM:] placeholder as a blocking issue.
export const DESCRIPTION_PLACEHOLDER =
  '[CONFIRM: describe what your app does in one or two sentences]';

export interface InitAnswers {
  description: string;
  audience: string[];
  requiresLogin: boolean | null;
  collectsPersonalData: boolean | null;
  countries: string[];
  locales: string[];
}

export function defaultAnswers(scan: ScanResult): InitAnswers {
  return {
    description: DESCRIPTION_PLACEHOLDER,
    audience: [],
    requiresLogin: null,
    // suggest true when the scanner already found data collection
    collectsPersonalData:
      Object.keys(scan.privacyReport.dataCollection).length > 0 ? true : null,
    countries: [],
    locales: ['en-US'],
  };
}

export function buildConfig(scan: ScanResult, answers: InitAnswers): AppshipConfig {
  const bundleId = scan.project.ios?.bundleId ?? null;
  const packageName = scan.project.android?.packageName ?? null;
  const locales = answers.locales.length > 0 ? answers.locales : ['en-US'];

  return appshipConfigSchema.parse({
    project: {
      name: scan.project.appName ?? 'My App',
      description: answers.description || DESCRIPTION_PLACEHOLDER,
      audience: answers.audience,
      ...(answers.requiresLogin === null ? {} : { requires_login: answers.requiresLogin }),
      ...(answers.collectsPersonalData === null
        ? {}
        : { collects_personal_data: answers.collectsPersonalData }),
    },
    platforms: {
      ...(bundleId ? { ios: { bundle_id: bundleId } } : {}),
      ...(packageName ? { android: { package_name: packageName } } : {}),
    },
    stores: {
      default_locale: locales[0],
      locales,
      countries: answers.countries,
    },
  });
}

export async function writeConfig(projectRoot: string, config: AppshipConfig): Promise<string> {
  const header =
    '# AppShip configuration\n' +
    '# Generated by `appship init` — edit freely, then run `appship generate`.\n' +
    '# API keys are read from environment variables and never stored here.\n';
  const path = join(projectRoot, CONFIG_FILENAME);
  await writeFile(path, header + stringify(config), 'utf8');
  return path;
}

export async function writeAnalysis(projectRoot: string, scan: ScanResult): Promise<string[]> {
  const analysisDir = join(projectRoot, APPSHIP_DIR, 'analysis');
  await mkdir(analysisDir, { recursive: true });

  const files: Array<[string, unknown]> = [
    ['project.json', scan.project],
    ['permissions.json', scan.permissions],
    ['sdk-report.json', scan.sdkReport],
    ['privacy-report.json', scan.privacyReport],
  ];
  const written: string[] = [];
  for (const [name, data] of files) {
    const path = join(analysisDir, name);
    await writeFile(path, JSON.stringify(data, null, 2) + '\n', 'utf8');
    written.push(path);
  }
  return written;
}

export interface InitResult {
  configPath: string;
  analysisPaths: string[];
  config: AppshipConfig;
}

export async function runInit(
  projectRoot: string,
  scan: ScanResult,
  answers: InitAnswers,
): Promise<InitResult> {
  const config = buildConfig(scan, answers);
  const [configPath, analysisPaths] = await Promise.all([
    writeConfig(projectRoot, config),
    writeAnalysis(projectRoot, scan),
  ]);
  return { configPath, analysisPaths, config };
}
