// appship export ci (MVP 3): GitHub Actions scaffolding. The readiness gate
// works out of the box (doctor is offline). The release workflow wires the
// appship upload/submit steps and fastlane auth secrets, but the build step
// is project-specific — it carries explicit TODO markers instead of guesses.

import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { AppshipConfig } from '../config/schema.js';
import type { GenerateTarget } from '../generate/index.js';

export class CIExportError extends Error {}

export interface CIExportOptions {
  target?: GenerateTarget;
  /** Overwrite existing workflow files. */
  force?: boolean;
  /** Expo managed project — changes the suggested Android build step. */
  isExpo?: boolean;
}

export interface CIExportResult {
  written: string[];
  skipped: string[];
}

export function readinessWorkflowContent(): string {
  return `# Generated by appship — release readiness gate.
# appship doctor runs fully offline and exits 1 on error-severity findings.
name: Release readiness

on:
  pull_request:

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx appship doctor
`;
}

const ANDROID_BUILD_STEPS_BARE = `      # TODO(appship): adjust to your release signing setup.
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build release bundle
        run: cd android && ./gradlew bundleRelease`;

const ANDROID_BUILD_STEPS_EXPO = `      # TODO(appship): this project uses Expo — either build with EAS
      # (eas build -p android --non-interactive) and download the artifact,
      # or prebuild and use gradle as below.
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build release bundle
        run: npx expo prebuild -p android --no-install && cd android && ./gradlew bundleRelease`;

export function releaseWorkflowContent(config: AppshipConfig, options: CIExportOptions): string {
  const wantIos = options.target !== 'android' && config.platforms.ios !== undefined;
  const wantAndroid = options.target !== 'ios' && config.platforms.android !== undefined;

  const jobs: string[] = [];

  if (wantAndroid) {
    jobs.push(`  android:
    if: \${{ inputs.platform == 'android' || inputs.platform == 'both' }}
    runs-on: ubuntu-latest
    env:
      # Play Console service account JSON — see fastlane supply docs.
      SUPPLY_JSON_KEY_DATA: \${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
${options.isExpo ? ANDROID_BUILD_STEPS_EXPO : ANDROID_BUILD_STEPS_BARE}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Upload to Play track
        run: npx appship upload android --track \${{ inputs.track }} --yes
      - name: Submit for review
        if: \${{ inputs.submit }}
        run: npx appship submit android --from-track \${{ inputs.track }} --yes`);
  }

  if (wantIos) {
    jobs.push(`  ios:
    if: \${{ inputs.platform == 'ios' || inputs.platform == 'both' }}
    runs-on: macos-latest
    env:
      # App Store Connect API key — see fastlane app_store_connect_api_key docs.
      APP_STORE_CONNECT_API_KEY_KEY_ID: \${{ secrets.ASC_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: \${{ secrets.ASC_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_KEY: \${{ secrets.ASC_KEY_CONTENT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      # TODO(appship): building a signed .ipa needs your certificates and
      # provisioning profiles in CI — fastlane match is the usual answer
      # (https://docs.fastlane.tools/actions/match/). Replace this step.
      - name: Build signed ipa
        run: 'echo "TODO: build a signed .ipa (e.g. fastlane gym after fastlane match)" && exit 1'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Upload to TestFlight
        run: npx appship upload ios --yes
      - name: Submit for review
        if: \${{ inputs.submit }}
        run: npx appship submit ios --yes`);
  }

  return `# Generated by appship — build, upload to test tracks, and optionally submit.
# Search for TODO(appship) and finish the build steps before first use.
name: Release

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform to release
        type: choice
        options: [${[wantIos ? 'ios' : null, wantAndroid ? 'android' : null, wantIos && wantAndroid ? 'both' : null].filter(Boolean).join(', ')}]
        required: true
      track:
        description: Play track for the android upload
        type: string
        default: internal
      submit:
        description: Also submit for store review (confirmation-gated by doctor)
        type: boolean
        default: false

jobs:
${jobs.join('\n\n')}
`;
}

export async function exportCI(
  projectRoot: string,
  config: AppshipConfig,
  options: CIExportOptions = {},
): Promise<CIExportResult> {
  const wantIos = options.target !== 'android' && config.platforms.ios !== undefined;
  const wantAndroid = options.target !== 'ios' && config.platforms.android !== undefined;
  if (!wantIos && !wantAndroid) {
    throw new CIExportError('No platforms configured in appship.yml for the requested target.');
  }

  const files: Array<[path: string, content: string]> = [
    [join('.github', 'workflows', 'appship-readiness.yml'), readinessWorkflowContent()],
    [join('.github', 'workflows', 'appship-release.yml'), releaseWorkflowContent(config, options)],
  ];

  const written: string[] = [];
  const skipped: string[] = [];
  for (const [path, content] of files) {
    const absolute = join(projectRoot, path);
    if (existsSync(absolute) && !options.force) {
      skipped.push(path);
      continue;
    }
    await mkdir(dirname(absolute), { recursive: true });
    await writeFile(absolute, content, 'utf8');
    written.push(path);
  }
  return { written, skipped };
}
